repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
        files: ^((pymammotion)/.+)?[^/]+\.(py|pyi)$

  - repo: https://github.com/JelleZijlstra/autotyping
    rev: master
    hooks:
      - id: autotyping
        stages: [ pre-commit ]
        types: [ python ]
        args: [ --safe ]
        files: ^((pymammotion)/.+)?[^/]+\.(py|pyi)$
  - repo: local
    hooks:
      - id: ty
        name: ty
        entry: uv run ty check
        language: system
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest tests/
        language: system
        pass_filenames: false
        always_run: true
