repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
        files: ^((pymammotion)/.+)?[^/]+\.(py|pyi)$

  - repo: https://github.com/JelleZijlstra/autotyping
    rev: master
    hooks:
      - id: autotyping
        stages: [ commit ]
        types: [ python ]
        args: [ --safe ]
        files: ^((pymammotion)/.+)?[^/]+\.(py|pyi)$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        exclude: ^(pymammotion/proto/|tests/|scripts/|pymammotion/mqtt/linkkit/)
