"""BLE command opcodes used by the Mammotion BLE protocol."""

from __future__ import annotations

from enum import IntEnum


class BleOrderCmd(IntEnum):
    """BLE command opcode identifiers used in the Mammotion protocol."""

    ALLPOWERFULL_RW = 67
    ALONG_BORDER = 9
    AREA_AND_TIME_AND_PATH_UPDATE = 27
    AUTO_UNDER_PILE = 65
    BATTERY_VALUE_UPDATE = 5
    BLE_ALIVE = 59
    CANCEL_CURRENT_RECORD = 62
    CANCEL_LOG_UPDATE = 45
    CANCEL_PAUSE_EXECUTE_TASK = 47
    CHECK_FRAMWARE_VERSION = 41
    CHECK_FRAMWARE_VERSION_CALL_BACK = 42
    CHECK_SOFT_VERSION = 35
    CHECK_SOFT_VERSION_CALL_BACK = 36
    CLOSE_KINFE = 50
    CLOSE_CLEAR_CONNECT_CURRENT_WIFI = 77
    DELETING_CONNECTION_PATH = 22
    DEVICE_ORDER_RESPONSE = 46
    DEVICE_STATUS_UPDATE = 31
    END_CHANNEL_LINE = 15
    END_DRAW_BARRIER = 13
    END_DRAW_BORDER = 11
    ERROR_CODE_UPDATE = 34
    FRAMWARE_PACKAGE_CALL_BACK = 40
    FRAMWARE_SUCCESS_UPDATE = 48
    FRAMWARE_UPDATE_CALL_BACK = 38
    GENERATE_ROUTE_INFORMATION = 210
    GET_AREA_DATA = 209
    GET_DEIVE_BORDER_STATE = 64
    GET_DEVICE_INFO = 63
    GET_DEVICE_LOG_INFO = 43
    GET_HASH_LIST = 208
    GET_RECORD_WIFI = 69
    INIT_POINT_UPDATE = 3
    JOB_PLAN_SETTING_READ_DELETE = 78
    JOB_PLAN_SETTING_READ_DELETE_UNABLE_TIME = 79
    KINFE_STATE = 51
    KNIFE_HIGHT_UPDATE = 29
    LOG_PROGRESS_UPDATE = 44
    OPEN_KINFE = 49
    OPTIMIZATION_BORDER_UPADATE = 17
    OPTIMIZATION_CHANNAL_LINE_UPDATE = 19
    OPTIMIZATION_OBSTACLE_UPDATE = 18
    ORIGIN_LAG_LOG = 52
    PAUSE_EXECUTE_TASK = 7
    REMOVE_OBSTACLES_OR_OBSTRUCTIONS = 21
    REPLY_OPTIMIZATION_PACKAGE = 20
    RESET_BASE_STATION = 61
    RESPONSE_DEVICE = 52
    RETRUN_GENERATE_ROUTE_INFORMATION = 211
    RETURN_CHARGE = 8
    RTLOACTION_UPDATE = 4
    SAVE_TASK = 16
    SEND_BORDER_PACKAGE = 21
    SEND_BORDER_PACKAGE_CALL_BACK = 22
    SEND_CHANNAL_LINE_PACKAGE = 25
    SEND_CHANNAL_LINE_PACKAGE_CALL_BACK = 26
    SEND_CONTRL_CALL_BACK = 2
    SEND_CONTROL = 1
    SEND_EXECUTE_TASK = 6
    SEND_FRAMWARE_PACKAGE = 39
    SEND_FRAMWARE_UPDATE = 37
    SEND_OBSTACLE_PACKAGE = 23
    SEND_OBSTACLE_PACKAGE_CALL_BACK = 24
    SEND_PLAN = 32
    SET_KNIFE_HIGHT = 28
    SET_MAX_SPEED = 33
    START_CHANNEL_LINE = 14
    START_DRAW_BARRIER = 12
    START_DRAW_BORDER = 10
    START_WORK_ORDER = 60
    START_JOB = 212
    SYN_TIME = 57
    TASK = 213
    TASK_PROGRESS_UPDATE = 30
    TEST_PW = 52
    WIFI_CONNECT_INFO_UPDATE = 68
    WIRTE_READ_SPEED = 66
