from typing import Any

from pymammotion.data.model.device_limits import DeviceLimits
from pymammotion.utility.device_type import DeviceType

default_luba_config = {
    "blade_height": {"min": 20, "max": 35},
    "working_speed": {"min": 0.2, "max": 1.2},
    "path_spacing": {"min": 20, "max": 35},
    "work_area_num_max": 60,
    "display_image_type": 0,
}

default_yuka_config = {
    "blade_height": {"min": 0, "max": 0},
    "working_speed": {"min": 0.2, "max": 0.6},
    "path_spacing": {"min": 8, "max": 14},
    "work_area_num_max": 60,
    "display_image_type": 0,
}


class DeviceConfig:
    """Per-product-key device capability configuration (blade height, speed, area limits)."""

    def __init__(self) -> None:
        # Dictionary to store all device configurations

        # Device mode configurations
        self.default_list: dict[str, dict[str, Any]] = {
            "a1ZU6bdGjaM": {
                "extMod": "LubaAWD1000723",
                "blade_height_min": 30,
                "blade_height_max": 70,
                "working_speed_min": 0.2,
                "working_speed_max": 0.4,
                "work_area_num_max": 3,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 1,
            },
            "a1nf9kRBWoH": {
                "extMod": "LubaAWD3000723",
                "blade_height_min": 30,
                "blade_height_max": 70,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 6,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 1,
            },
            "a1ae1QnXZGf": {
                "extMod": "LubaAWD1000743",
                "blade_height_min": 30,
                "blade_height_max": 70,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 3,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 1,
            },
            "a1K4Ki2L5rK": {
                "extMod": "LubaAWD5000723",
                "blade_height_min": 30,
                "blade_height_max": 70,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 10,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "a1jOhAYOIG8": {
                "extMod": "LubaAWD5000743LS",
                "blade_height_min": 30,
                "blade_height_max": 70,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 10,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "a1BmXWlsdbA": {
                "extMod": "LubaAWD5000743",
                "blade_height_min": 30,
                "blade_height_max": 70,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 10,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "a1JFpmAV5Ur": {
                "extMod": "Kumar-10",
                "blade_height_min": 30,
                "blade_height_max": 70,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 10,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "a1kweSOPylG": {
                "extMod": "LubaAWD3000723",
                "blade_height_min": 30,
                "blade_height_max": 70,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 6,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 1,
            },
            "a1pvCnb3PPu": {
                "extMod": "LubaAWD1000743",
                "blade_height_min": 30,
                "blade_height_max": 70,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 3,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 1,
            },
            "a1x0zHD3Xop": {
                "extMod": "LubaAWD5000743LS",
                "blade_height_min": 30,
                "blade_height_max": 70,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 10,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "a1UBFdq6nNz": {
                "extMod": "LubaAWD5000723",
                "blade_height_min": 30,
                "blade_height_max": 70,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 10,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "a1FbaU4Bqk5": {
                "extMod": "LubaAWD5000743",
                "blade_height_min": 30,
                "blade_height_max": 70,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 10,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
        }

        self.inner_list: dict[str, dict[str, Any]] = {
            "HM010060LBAWD10": {
                "extMod": "LubaAWD1000",
                "blade_height_min": 30,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 3,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 1,
            },
            "HM030080LBAWD30": {
                "extMod": "LubaAWD3000",
                "blade_height_min": 30,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 6,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 1,
            },
            "HM050080LBAWD50": {
                "extMod": "LubaAWD5000",
                "blade_height_min": 30,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 10,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM030060LBAWD50OMNI": {
                "extMod": "LubaAWD5000",
                "blade_height_min": 30,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 10,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 1,
            },
            "HM060100LBAWD50OMNIH": {
                "extMod": "LubaAWD5000H",
                "blade_height_min": 60,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 10,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM030070LBVAWD10OMNI": {
                "extMod": "Luba2AWD1000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 10,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM060100LBVAWD10OMNIH": {
                "extMod": "Luba2AWD1000H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 10,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM030070LBVAWD30OMNI": {
                "extMod": "Luba2AWD3000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 20,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM060100LBVAWD30OMNIH": {
                "extMod": "Luba2AWD3000H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 20,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM030070LBVAWD50OMNI": {
                "extMod": "Luba2AWD5000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 30,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM060100LBVAWD50OMNIH": {
                "extMod": "Luba2AWD5000H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 30,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM030070LBVAWD100OMNI": {
                "extMod": "Luba2AWD10000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM060100LBVAWD100OMNIH": {
                "extMod": "Luba2AWD10000H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM030070LB2PAWD30OMNI": {
                "extMod": "LUBA 2 AWD 3000X",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM060100LB2PAWD30OMNIH": {
                "extMod": "LUBA 2 AWD 3000HX",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM030070LB2PAWD50OMNI": {
                "extMod": "LUBA 2 AWD 5000X",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 0.8,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM060100LB2PAWD50OMNIH": {
                "extMod": "LUBA 2 AWD 5000HX",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 0.8,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM030070LB2PAWD100OMNI": {
                "extMod": "LUBA 2 AWD 10000X",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 0.8,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM060100LB2PAWD100OMNIH": {
                "extMod": "LUBA 2 AWD 10000HX",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 0.8,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM020065LB2MINIAWD08OMNI": {
                "extMod": "LUBA mini AWD 800",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 14,
                "display_image_type": 0,
            },
            "HM020065LB2MINIAWD12OMNILD": {
                "extMod": "Luba2 AWD Lidar",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "HM020065LB2MINIAWD15OMNI": {
                "extMod": "LUBA mini AWD 1500",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 14,
                "display_image_type": 0,
            },
            "HM020065LB2MINIAWD15OMNILD": {
                "extMod": "Luba2MiniAWD1500Lidar",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 5,
                "path_spacing_max": 20,
                "display_image_type": 0,
            },
            "HM055100LB2MINIAWD08OMNIH": {
                "extMod": "LUBA mini AWD 800H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 14,
                "display_image_type": 0,
            },
            "HM055100LB2MINIAWD15OMNIH": {
                "extMod": "LUBA mini AWD 1500H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 14,
                "display_image_type": 0,
            },
            "HM055100LB2MINIAWD15OMNIHLD": {
                "extMod": "Luba2MiniAWD1500NALidar",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 5,
                "path_spacing_max": 20,
                "display_image_type": 0,
            },
            "HM030070YK06": {
                "extMod": "Yuka600",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "HM030100YK06H": {
                "extMod": "Yuka600NA",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "HM030070YK10": {
                "extMod": "Yuka1000",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "HM030100YK10H": {
                "extMod": "Yuka1000",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "HM030070YK15": {
                "extMod": "Yuka1500",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "HM030100YK15H": {
                "extMod": "Yuka1500",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "HM020090YK20": {
                "extMod": "Yuka2000",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "HM030100YK20H": {
                "extMod": "Yuka2000",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "HM020080YKMINI05": {
                "extMod": "YUKA mini 500",
                "blade_height_min": 20,
                "blade_height_max": 60,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "HM050090YKMINI05H": {
                "extMod": "YUKA mini 500",
                "blade_height_min": 50,
                "blade_height_max": 90,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "HM020080YKMINI08": {
                "extMod": "YUKA mini 800",
                "blade_height_min": 20,
                "blade_height_max": 60,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "HM050090YKMINI08H": {
                "extMod": "YUKA mini 800",
                "blade_height_min": 50,
                "blade_height_max": 90,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "HM020080YKMINI06": {
                "extMod": "YUKA mini 600",
                "blade_height_min": 20,
                "blade_height_max": 60,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "HM020080YKMINI07": {
                "extMod": "YUKA mini 700",
                "blade_height_min": 20,
                "blade_height_max": 60,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "HM050090YKMINI06H": {
                "extMod": "YUKA mini 600",
                "blade_height_min": 50,
                "blade_height_max": 90,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "HM050090YKMINI07H": {
                "extMod": "YUKA mini 700",
                "blade_height_min": 50,
                "blade_height_max": 90,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "HM020080YKMINIV07": {
                "extMod": "YUKA mini Vision 500",
                "blade_height_min": 50,
                "blade_height_max": 90,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "HM020080YKMINI09": {
                "extMod": "YUKA mini Vision 700",
                "blade_height_min": 50,
                "blade_height_max": 90,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "HM020080YKMINIV09": {
                "extMod": "YUKA mini Vision 800",
                "blade_height_min": 50,
                "blade_height_max": 90,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "HM020090YKPLUS15": {
                "extMod": "YUKA 1000",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "HM020090YKPLUS20": {
                "extMod": "YUKA 2000",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "HM030100YKPLUS15H": {
                "extMod": "YUKA 1000",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "HM030100YKPLUS20H": {
                "extMod": "YUKA 2000",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "HM030080LB2PAWD30OMNI": {
                "extMod": "LUBA AWD 3000 Vision",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM020080MN23103": {
                "extMod": "MN231_1",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "HM020060YKMNL10": {
                "extMod": "YUKA mini 2 1000",
                "blade_height_min": 20,
                "blade_height_max": 60,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "HM020065LB2MINIAWDL10OMNI": {
                "extMod": "LUBA mini AWD LIDAR 1000",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "HM020065LB2MINIAWDLA20OMNI": {
                "extMod": "LUBA mini AWD 360 LIDAR 2000",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 14,
                "display_image_type": 0,
            },
            "100": {
                "extMod": "MN100",
                "blade_height_min": 50,
                "blade_height_max": 90,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "117": {
                "extMod": "MN101",
                "blade_height_min": 50,
                "blade_height_max": 90,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "HM020065LB2MINIAWDL20OMNI": {
                "extMod": "LUBA mini AWD LIDAR 2000",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "101": {
                "extMod": "LUBA mini Vision 1000",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "105": {
                "extMod": "LUBA mini Vision 1000",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "125": {
                "extMod": "LUBA mini Vision 1000",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "126": {
                "extMod": "LUBA mini Vision 1000",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "127": {
                "extMod": "LUBA mini Vision 1000",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "128": {
                "extMod": "LUBA mini Vision 1000H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "HM025070LB2PAWDL10OMNI": {
                "extMod": "LUBA 3 AWD 150",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "61": {
                "extMod": "LUBA 3 AWD 1500",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "121": {
                "extMod": "LUBA 3 AWD 1500",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "122": {
                "extMod": "LUBA 3 AWD 1500",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "107": {
                "extMod": "LUBA 3 AWD 1500",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM055100LB2PAWDL10OMNIH": {
                "extMod": "LUBA 3 AWD 1500H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "62": {
                "extMod": "LUBA 3 AWD 1500H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "108": {
                "extMod": "LUBA 3 AWD 1500H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM025070LB2PAWDL30OMNI": {
                "extMod": "LUBA 3 AWD 3000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "63": {
                "extMod": "LUBA 3 AWD 3000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "123": {
                "extMod": "LUBA 3 AWD 3000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "109": {
                "extMod": "LUBA 3 AWD 3000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM055100LB2PAWDL30OMNIH": {
                "extMod": "LUBA 3 AWD 3000H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "64": {
                "extMod": "LUBA 3 AWD 3000H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "110": {
                "extMod": "LUBA 3 AWD 3000H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM025070LB2PAWDL50OMNI": {
                "extMod": "LUBA 3 AWD 5000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "65": {
                "extMod": "LUBA 3 AWD 5000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "124": {
                "extMod": "LUBA 3 AWD 5000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "116": {
                "extMod": "LUBA 3 AWD 5000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM055100LB2PAWDL50OMNIH": {
                "extMod": "LUBA 3 AWD 5000H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "66": {
                "extMod": "LUBA 3 AWD 5000H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "114": {
                "extMod": "LUBA 3 AWD 5000H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM025070LB2PAWDL100OMNI": {
                "extMod": "LUBA 3 AWD 10000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "67": {
                "extMod": "LUBA 3 AWD 10000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "111": {
                "extMod": "LUBA 3 AWD 10000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "HM055100LB2PAWDL100OMNIH": {
                "extMod": "LUBA 3 AWD 10000H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "68": {
                "extMod": "LUBA 3 AWD 10000H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "112": {
                "extMod": "LUBA 3 AWD 10000H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "104": {
                "extMod": "LUBA 3 AWD 5000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "115": {
                "extMod": "LUBA 3 AWD 5000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "119": {
                "extMod": "LUBA 3 AWD 3000NA",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "55": {
                "extMod": "YUKA mini 2 1000",
                "blade_height_min": 20,
                "blade_height_max": 60,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "103": {
                "extMod": "YUKA mini 2 1000",
                "blade_height_min": 20,
                "blade_height_max": 60,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "120": {
                "extMod": "YUKA mini 2 1000",
                "blade_height_min": 20,
                "blade_height_max": 60,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "118": {
                "extMod": "YUKA mini 2 1000",
                "blade_height_min": 20,
                "blade_height_max": 60,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "136": {
                "extMod": "YUKA mini 2 600",
                "blade_height_min": 20,
                "blade_height_max": 60,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "56": {
                "extMod": "LUBA mini AWD LIDAR 2000",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "71": {
                "extMod": "",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 14,
                "display_image_type": 0,
            },
            "72": {
                "extMod": "",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 14,
                "display_image_type": 0,
            },
            "70": {
                "extMod": "LUBA mini AWD 360 LIDAR 1500",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 14,
                "display_image_type": 0,
            },
            "106": {
                "extMod": "LUBA mini AWD 360 LIDAR 1500",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 14,
                "display_image_type": 0,
            },
            "129": {
                "extMod": "LUBA mini AWD 360 LIDAR 1500",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 14,
                "display_image_type": 0,
            },
            "130": {
                "extMod": "LUBA mini AWD 360 LIDAR 1500",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 14,
                "display_image_type": 0,
            },
            "131": {
                "extMod": "LUBA mini AWD 360 LIDAR 1500",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 14,
                "display_image_type": 0,
            },
            "132": {
                "extMod": "LUBA mini AWD 360 LIDAR 1500",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 14,
                "display_image_type": 0,
            },
            "133": {
                "extMod": "LUBA mini AWD 360 LIDAR 1500H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 14,
                "display_image_type": 0,
            },
            "CM900A01": {
                "extMod": "CM900A01",
                "blade_height_min": 20,
                "blade_height_max": 90,
                "cutting_speed_min": 0.5,
                "cutting_speed_max": 1.5,
                "working_speed_min": 0.5,
                "working_speed_max": 2,
                "work_area_num_max": 10,
                "path_spacing_min": 20,
                "path_spacing_max": 70,
                "display_image_type": 0,
            },
            "58": {
                "extMod": "CM900A01",
                "blade_height_min": 20,
                "blade_height_max": 90,
                "cutting_speed_min": 0.5,
                "cutting_speed_max": 1.5,
                "working_speed_min": 0.5,
                "working_speed_max": 2,
                "work_area_num_max": 10,
                "path_spacing_min": 20,
                "path_spacing_max": 70,
                "display_image_type": 0,
            },
            "141": {
                "extMod": "CM901",
                "blade_height_min": 20,
                "blade_height_max": 90,
                "cutting_speed_min": 0.5,
                "cutting_speed_max": 1.5,
                "working_speed_min": 0.5,
                "working_speed_max": 2,
                "work_area_num_max": 10,
                "path_spacing_min": 20,
                "path_spacing_max": 70,
                "display_image_type": 0,
            },
            "49": {
                "extMod": "YUKA mini Vision 500",
                "blade_height_min": 50,
                "blade_height_max": 90,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "48": {
                "extMod": "YUKA mini Vision 700",
                "blade_height_min": 50,
                "blade_height_max": 90,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "50": {
                "extMod": "YUKA mini Vision 800",
                "blade_height_min": 50,
                "blade_height_max": 90,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "37": {
                "extMod": "YUKA mini 600",
                "blade_height_min": 20,
                "blade_height_max": 60,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "38": {
                "extMod": "YUKA mini 700",
                "blade_height_min": 20,
                "blade_height_max": 60,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "39": {
                "extMod": "YUKA mini 600H",
                "blade_height_min": 50,
                "blade_height_max": 90,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "40": {
                "extMod": "YUKA mini 700H",
                "blade_height_min": 50,
                "blade_height_max": 90,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "41": {
                "extMod": "YUKA 1000",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "42": {
                "extMod": "YUKA 2000",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "43": {
                "extMod": "YUKA 1000",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "44": {
                "extMod": "YUKA 2000",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "45": {
                "extMod": "MN231_1",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "46": {
                "extMod": "YUKA 3000",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "HM020090YKPLUS30": {
                "extMod": "YUKA 3000",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "47": {
                "extMod": "YUKA 3000",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "HM030100YKPLUS30H": {
                "extMod": "YUKA 3000",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "35": {
                "extMod": "LUBA mini AWD 1500H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 14,
                "display_image_type": 0,
            },
            "34": {
                "extMod": "LUBA mini AWD 800H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 14,
                "display_image_type": 0,
            },
            "33": {
                "extMod": "Luba2 AWD Lidar",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "32": {
                "extMod": "LUBA mini AWD 1500",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 14,
                "display_image_type": 0,
            },
            "31": {
                "extMod": "LUBA mini AWD 800",
                "blade_height_min": 20,
                "blade_height_max": 65,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 14,
                "display_image_type": 0,
            },
            "30": {
                "extMod": "YUKA mini 500",
                "blade_height_min": 50,
                "blade_height_max": 90,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "29": {
                "extMod": "YUKA mini 800H",
                "blade_height_min": 50,
                "blade_height_max": 90,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "28": {
                "extMod": "LUBA 2 AWD 10000HX",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 0.8,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "27": {
                "extMod": "LUBA 2 AWD 10000X",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 0.8,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "26": {
                "extMod": "LUBA 2 AWD 5000HX",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 0.8,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "25": {
                "extMod": "LUBA 2 AWD 5000X",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 0.8,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "24": {
                "extMod": "LUBA 2 AWD 3000HX",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "23": {
                "extMod": "LUBA 2 AWD 3000X",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "22": {
                "extMod": "Yuka2000",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "21": {
                "extMod": "Yuka2000",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "20": {
                "extMod": "YUKA mini 500",
                "blade_height_min": 20,
                "blade_height_max": 60,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "19": {
                "extMod": "YUKA mini 800",
                "blade_height_min": 20,
                "blade_height_max": 60,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 8,
                "path_spacing_max": 12,
                "display_image_type": 0,
            },
            "18": {
                "extMod": "Yuka1500",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "17": {
                "extMod": "Yuka1000",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "15": {
                "extMod": "Yuka1500",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "14": {
                "extMod": "Yuka1000",
                "blade_height_min": 55,
                "blade_height_max": 55,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 15,
                "path_spacing_max": 30,
                "display_image_type": 0,
            },
            "12": {
                "extMod": "Luba2AWD10000H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "11": {
                "extMod": "Luba2AWD10000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "10": {
                "extMod": "Luba2AWD3000H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 20,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "9": {
                "extMod": "Luba2AWD3000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 20,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "8": {
                "extMod": "Luba2AWD1000H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 10,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "7": {
                "extMod": "Luba2AWD1000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 10,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "6": {
                "extMod": "Luba2AWD5000H",
                "blade_height_min": 55,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 30,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "5": {
                "extMod": "Luba2AWD5000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 30,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "4": {
                "extMod": "LubaAWD5000H",
                "blade_height_min": 60,
                "blade_height_max": 100,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 10,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "3": {
                "extMod": "LubaAWD5000",
                "blade_height_min": 30,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 10,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 1,
            },
            "2": {
                "extMod": "LubaAWD1000",
                "blade_height_min": 30,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 3,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 1,
            },
            "1": {
                "extMod": "LubaAWD3000",
                "blade_height_min": 30,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 6,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 1,
            },
            "0": {
                "extMod": "LubaAWD5000",
                "blade_height_min": 30,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 10,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "137": {
                "extMod": "LUBA 4 AWD 3000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "138": {
                "extMod": "LUBA 4 AWD 5000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
            "139": {
                "extMod": "LUBA 4 AWD 10000",
                "blade_height_min": 25,
                "blade_height_max": 70,
                "cutting_speed_min": 0.2,
                "cutting_speed_max": 0.6,
                "working_speed_min": 0.2,
                "working_speed_max": 1.2,
                "work_area_num_max": 60,
                "path_spacing_min": 20,
                "path_spacing_max": 35,
                "display_image_type": 0,
            },
        }

    def get_device_config(self, int_mod_or_key: str) -> dict[str, Any] | None:
        """Look up device configuration by internal model code

        Args:
            int_mod (str): Internal model code

        Returns:
            dict: Device configuration or None if not found
            :param int_mod_or_key:

        """
        if found := self.inner_list.get(int_mod_or_key) or (found := self.default_list.get(int_mod_or_key)):
            return found
        return None

    def get_external_model(self, int_mod: str) -> str | None:
        """Get external model name for given internal model code

        Args:
            int_mod (str): Internal model code

        Returns:
            str: External model name or None if not found

        """
        config = self.get_device_config(int_mod)
        return config.get("extMod") if config else None

    def get_working_parameters(self, int_mod_or_key: str) -> DeviceLimits | None:
        """Get working parameters for given internal model code

        Args:
            int_mod (str): Internal model code

        Returns:
            dict: Working parameters or None if not found
            :param int_mod_or_key:

        """
        if config := self.get_device_config(int_mod_or_key):
            return DeviceLimits.from_dict(
                {
                    "blade_height": {"min": config["blade_height_min"], "max": config["blade_height_max"]},
                    "working_speed": {"min": config["working_speed_min"], "max": config["working_speed_max"]},
                    "path_spacing": {"min": config["path_spacing_min"], "max": config["path_spacing_max"]},
                    "work_area_num_max": config["work_area_num_max"],
                    "display_image_type": config["display_image_type"],
                }
            )
        return None

    @staticmethod
    def get_best_default(product_key: str) -> DeviceLimits:
        """Basic fallback if device is offline."""

        if DeviceType.contain_luba_product_key(product_key):
            return DeviceLimits.from_dict(default_luba_config)
        if DeviceType.contain_luba_2_product_key(product_key):
            return DeviceLimits.from_dict(default_luba_config)

        return DeviceLimits.from_dict(default_yuka_config)
