# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pymammotion/proto/pdt.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bpymammotion/proto/pdt.proto\"N\n\rModulesFwInfo\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x14\n\x0c\x63omponent_id\x18\x02 \x01(\t\x12\x19\n\x11\x63omponent_version\x18\x03 \x01(\t\"_\n\x0fPdtDeviceFwInfo\x12\x16\n\x0e\x64\x65vice_version\x18\x01 \x01(\t\x12$\n\x0cmodules_info\x18\x02 \x03(\x0b\x32\x0e.ModulesFwInfo\x12\x0e\n\x06result\x18\x03 \x01(\x05\"#\n\x0bModulesName\x12\x14\n\x0cmodules_name\x18\x01 \x01(\t\"/\n\x07PdtItem\x12\x10\n\x08\x64\x61ta_msg\x18\x01 \x01(\t\x12\x12\n\ndata_state\x18\x02 \x01(\x05\"3\n\nPdtInfoReq\x12\x13\n\x0bsesstion_id\x18\x01 \x01(\t\x12\x10\n\x08pdt_type\x18\x02 \x01(\x05\"\xa0\x01\n\nPdtInfoRsp\x12\x13\n\x0bsesstion_id\x18\x01 \x01(\t\x12\x1f\n\x07modules\x18\x02 \x01(\x0b\x32\x0c.ModulesNameH\x00\x12\x1c\n\x08pdt_data\x18\x03 \x01(\x0b\x32\x08.PdtItemH\x00\x12&\n\nfw_version\x18\x04 \x01(\x0b\x32\x10.PdtDeviceFwInfoH\x00\x42\x16\n\x14pdt_info_rsp_details\"\x1d\n\nPdtTestMod\x12\x0f\n\x07testmod\x18\x01 \x01(\x05\"$\n\nPdtTestReq\x12\x16\n\x0e\x63ontrol_result\x18\x01 \x01(\x05\"\xe3\x01\n\nPdtMessage\x12.\n\x17to_dev_get_pdt_info_req\x18\x01 \x01(\x0b\x32\x0b.PdtInfoReqH\x00\x12.\n\x17to_app_get_pdt_info_rsp\x18\x02 \x01(\x0b\x32\x0b.PdtInfoRspH\x00\x12\x32\n\x1bto_dev_control_pdt_test_req\x18\x03 \x01(\x0b\x32\x0b.PdtTestModH\x00\x12\x31\n\x1ato_app_result_pdt_test_rsp\x18\x04 \x01(\x0b\x32\x0b.PdtTestReqH\x00\x42\x0e\n\x0csub_pdt_typeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pymammotion.proto.pdt_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODULESFWINFO._serialized_start=31
  _MODULESFWINFO._serialized_end=109
  _PDTDEVICEFWINFO._serialized_start=111
  _PDTDEVICEFWINFO._serialized_end=206
  _MODULESNAME._serialized_start=208
  _MODULESNAME._serialized_end=243
  _PDTITEM._serialized_start=245
  _PDTITEM._serialized_end=292
  _PDTINFOREQ._serialized_start=294
  _PDTINFOREQ._serialized_end=345
  _PDTINFORSP._serialized_start=348
  _PDTINFORSP._serialized_end=508
  _PDTTESTMOD._serialized_start=510
  _PDTTESTMOD._serialized_end=539
  _PDTTESTREQ._serialized_start=541
  _PDTTESTREQ._serialized_end=577
  _PDTMESSAGE._serialized_start=580
  _PDTMESSAGE._serialized_end=807
# @@protoc_insertion_point(module_scope)
