# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pymammotion/proto/spino_ctrl.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"pymammotion/proto/spino_ctrl.proto\"\xf3\x02\n\nPlanJobSet\x12\x0b\n\x03\x63md\x18\x01 \x01(\x05\x12\x11\n\twork_mode\x18\x02 \x01(\x05\x12\x10\n\x08sub_mode\x18\x03 \x01(\x05\x12\x0e\n\x06userid\x18\x04 \x01(\t\x12\x10\n\x08\x64\x65viceid\x18\x05 \x01(\t\x12\x11\n\tstarttime\x18\x06 \x01(\x05\x12\x14\n\x0ctotalplannum\x18\x07 \x01(\x05\x12\x11\n\tplanindex\x18\x08 \x01(\x05\x12\x0e\n\x06result\x18\t \x01(\x05\x12\r\n\x05speed\x18\n \x01(\x07\x12\x17\n\x0foperating_power\x18\x0b \x01(\x07\x12\x0f\n\x07jobname\x18\x0c \x01(\t\x12\r\n\x05jobid\x18\r \x01(\t\x12\x11\n\tstartdate\x18\x0e \x01(\t\x12\x0f\n\x07\x65nddate\x18\x0f \x01(\t\x12\x13\n\x0btriggertype\x18\x10 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x11 \x01(\x05\x12\r\n\x05weeks\x18\x12 \x03(\x05\x12\x18\n\x10remained_seconds\x18\x13 \x01(\x05\x12\x0e\n\x06\x65nable\x18\x14 \x01(\x05\".\n\tSpinoCtrl\x12!\n\x0cplan_job_set\x18\x01 \x01(\x0b\x32\x0b.PlanJobSetb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pymammotion.proto.spino_ctrl_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLANJOBSET._serialized_start=39
  _PLANJOBSET._serialized_end=410
  _SPINOCTRL._serialized_start=412
  _SPINOCTRL._serialized_end=458
# @@protoc_insertion_point(module_scope)
