// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: esp_driver.proto

public final class EspDriver {
  private EspDriver() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommEspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CommEsp)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code CommEsp}
   */
  public static final class CommEsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CommEsp)
      CommEspOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommEsp.newBuilder() to construct.
    private CommEsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommEsp() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CommEsp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CommEsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EspDriver.internal_static_CommEsp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EspDriver.internal_static_CommEsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EspDriver.CommEsp.class, EspDriver.CommEsp.Builder.class);
    }

    public interface DrvDevInfoReqIdOrBuilder extends
        // @@protoc_insertion_point(interface_extends:CommEsp.DrvDevInfoReqId)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      int getId();

      /**
       * <code>int32 type = 2;</code>
       * @return The type.
       */
      int getType();
    }
    /**
     * Protobuf type {@code CommEsp.DrvDevInfoReqId}
     */
    public static final class DrvDevInfoReqId extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:CommEsp.DrvDevInfoReqId)
        DrvDevInfoReqIdOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use DrvDevInfoReqId.newBuilder() to construct.
      private DrvDevInfoReqId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private DrvDevInfoReqId() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new DrvDevInfoReqId();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private DrvDevInfoReqId(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                id_ = input.readInt32();
                break;
              }
              case 16: {

                type_ = input.readInt32();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EspDriver.internal_static_CommEsp_DrvDevInfoReqId_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EspDriver.internal_static_CommEsp_DrvDevInfoReqId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EspDriver.CommEsp.DrvDevInfoReqId.class, EspDriver.CommEsp.DrvDevInfoReqId.Builder.class);
      }

      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }

      public static final int TYPE_FIELD_NUMBER = 2;
      private int type_;
      /**
       * <code>int32 type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (id_ != 0) {
          output.writeInt32(1, id_);
        }
        if (type_ != 0) {
          output.writeInt32(2, type_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (id_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, id_);
        }
        if (type_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, type_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof EspDriver.CommEsp.DrvDevInfoReqId)) {
          return super.equals(obj);
        }
        EspDriver.CommEsp.DrvDevInfoReqId other = (EspDriver.CommEsp.DrvDevInfoReqId) obj;

        if (getId()
            != other.getId()) return false;
        if (getType()
            != other.getType()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static EspDriver.CommEsp.DrvDevInfoReqId parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static EspDriver.CommEsp.DrvDevInfoReqId parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static EspDriver.CommEsp.DrvDevInfoReqId parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static EspDriver.CommEsp.DrvDevInfoReqId parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static EspDriver.CommEsp.DrvDevInfoReqId parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static EspDriver.CommEsp.DrvDevInfoReqId parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static EspDriver.CommEsp.DrvDevInfoReqId parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static EspDriver.CommEsp.DrvDevInfoReqId parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static EspDriver.CommEsp.DrvDevInfoReqId parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static EspDriver.CommEsp.DrvDevInfoReqId parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static EspDriver.CommEsp.DrvDevInfoReqId parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static EspDriver.CommEsp.DrvDevInfoReqId parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(EspDriver.CommEsp.DrvDevInfoReqId prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code CommEsp.DrvDevInfoReqId}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:CommEsp.DrvDevInfoReqId)
          EspDriver.CommEsp.DrvDevInfoReqIdOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return EspDriver.internal_static_CommEsp_DrvDevInfoReqId_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return EspDriver.internal_static_CommEsp_DrvDevInfoReqId_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  EspDriver.CommEsp.DrvDevInfoReqId.class, EspDriver.CommEsp.DrvDevInfoReqId.Builder.class);
        }

        // Construct using EspDriver.CommEsp.DrvDevInfoReqId.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          id_ = 0;

          type_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return EspDriver.internal_static_CommEsp_DrvDevInfoReqId_descriptor;
        }

        @java.lang.Override
        public EspDriver.CommEsp.DrvDevInfoReqId getDefaultInstanceForType() {
          return EspDriver.CommEsp.DrvDevInfoReqId.getDefaultInstance();
        }

        @java.lang.Override
        public EspDriver.CommEsp.DrvDevInfoReqId build() {
          EspDriver.CommEsp.DrvDevInfoReqId result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public EspDriver.CommEsp.DrvDevInfoReqId buildPartial() {
          EspDriver.CommEsp.DrvDevInfoReqId result = new EspDriver.CommEsp.DrvDevInfoReqId(this);
          result.id_ = id_;
          result.type_ = type_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof EspDriver.CommEsp.DrvDevInfoReqId) {
            return mergeFrom((EspDriver.CommEsp.DrvDevInfoReqId)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(EspDriver.CommEsp.DrvDevInfoReqId other) {
          if (other == EspDriver.CommEsp.DrvDevInfoReqId.getDefaultInstance()) return this;
          if (other.getId() != 0) {
            setId(other.getId());
          }
          if (other.getType() != 0) {
            setType(other.getType());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          EspDriver.CommEsp.DrvDevInfoReqId parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (EspDriver.CommEsp.DrvDevInfoReqId) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int id_ ;
        /**
         * <code>int32 id = 1;</code>
         * @return The id.
         */
        @java.lang.Override
        public int getId() {
          return id_;
        }
        /**
         * <code>int32 id = 1;</code>
         * @param value The id to set.
         * @return This builder for chaining.
         */
        public Builder setId(int value) {
          
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 id = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearId() {
          
          id_ = 0;
          onChanged();
          return this;
        }

        private int type_ ;
        /**
         * <code>int32 type = 2;</code>
         * @return The type.
         */
        @java.lang.Override
        public int getType() {
          return type_;
        }
        /**
         * <code>int32 type = 2;</code>
         * @param value The type to set.
         * @return This builder for chaining.
         */
        public Builder setType(int value) {
          
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 type = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearType() {
          
          type_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:CommEsp.DrvDevInfoReqId)
      }

      // @@protoc_insertion_point(class_scope:CommEsp.DrvDevInfoReqId)
      private static final EspDriver.CommEsp.DrvDevInfoReqId DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new EspDriver.CommEsp.DrvDevInfoReqId();
      }

      public static EspDriver.CommEsp.DrvDevInfoReqId getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<DrvDevInfoReqId>
          PARSER = new com.google.protobuf.AbstractParser<DrvDevInfoReqId>() {
        @java.lang.Override
        public DrvDevInfoReqId parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new DrvDevInfoReqId(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<DrvDevInfoReqId> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<DrvDevInfoReqId> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public EspDriver.CommEsp.DrvDevInfoReqId getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface DrvDevInfoReqOrBuilder extends
        // @@protoc_insertion_point(interface_extends:CommEsp.DrvDevInfoReq)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
       */
      java.util.List<EspDriver.CommEsp.DrvDevInfoReqId> 
          getReqIdsList();
      /**
       * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
       */
      EspDriver.CommEsp.DrvDevInfoReqId getReqIds(int index);
      /**
       * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
       */
      int getReqIdsCount();
      /**
       * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
       */
      java.util.List<? extends EspDriver.CommEsp.DrvDevInfoReqIdOrBuilder> 
          getReqIdsOrBuilderList();
      /**
       * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
       */
      EspDriver.CommEsp.DrvDevInfoReqIdOrBuilder getReqIdsOrBuilder(
          int index);
    }
    /**
     * Protobuf type {@code CommEsp.DrvDevInfoReq}
     */
    public static final class DrvDevInfoReq extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:CommEsp.DrvDevInfoReq)
        DrvDevInfoReqOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use DrvDevInfoReq.newBuilder() to construct.
      private DrvDevInfoReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private DrvDevInfoReq() {
        reqIds_ = java.util.Collections.emptyList();
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new DrvDevInfoReq();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private DrvDevInfoReq(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  reqIds_ = new java.util.ArrayList<EspDriver.CommEsp.DrvDevInfoReqId>();
                  mutable_bitField0_ |= 0x00000001;
                }
                reqIds_.add(
                    input.readMessage(EspDriver.CommEsp.DrvDevInfoReqId.parser(), extensionRegistry));
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) != 0)) {
            reqIds_ = java.util.Collections.unmodifiableList(reqIds_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EspDriver.internal_static_CommEsp_DrvDevInfoReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EspDriver.internal_static_CommEsp_DrvDevInfoReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EspDriver.CommEsp.DrvDevInfoReq.class, EspDriver.CommEsp.DrvDevInfoReq.Builder.class);
      }

      public static final int REQ_IDS_FIELD_NUMBER = 1;
      private java.util.List<EspDriver.CommEsp.DrvDevInfoReqId> reqIds_;
      /**
       * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
       */
      @java.lang.Override
      public java.util.List<EspDriver.CommEsp.DrvDevInfoReqId> getReqIdsList() {
        return reqIds_;
      }
      /**
       * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
       */
      @java.lang.Override
      public java.util.List<? extends EspDriver.CommEsp.DrvDevInfoReqIdOrBuilder> 
          getReqIdsOrBuilderList() {
        return reqIds_;
      }
      /**
       * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
       */
      @java.lang.Override
      public int getReqIdsCount() {
        return reqIds_.size();
      }
      /**
       * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
       */
      @java.lang.Override
      public EspDriver.CommEsp.DrvDevInfoReqId getReqIds(int index) {
        return reqIds_.get(index);
      }
      /**
       * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
       */
      @java.lang.Override
      public EspDriver.CommEsp.DrvDevInfoReqIdOrBuilder getReqIdsOrBuilder(
          int index) {
        return reqIds_.get(index);
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (int i = 0; i < reqIds_.size(); i++) {
          output.writeMessage(1, reqIds_.get(i));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < reqIds_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, reqIds_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof EspDriver.CommEsp.DrvDevInfoReq)) {
          return super.equals(obj);
        }
        EspDriver.CommEsp.DrvDevInfoReq other = (EspDriver.CommEsp.DrvDevInfoReq) obj;

        if (!getReqIdsList()
            .equals(other.getReqIdsList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getReqIdsCount() > 0) {
          hash = (37 * hash) + REQ_IDS_FIELD_NUMBER;
          hash = (53 * hash) + getReqIdsList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static EspDriver.CommEsp.DrvDevInfoReq parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static EspDriver.CommEsp.DrvDevInfoReq parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static EspDriver.CommEsp.DrvDevInfoReq parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static EspDriver.CommEsp.DrvDevInfoReq parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static EspDriver.CommEsp.DrvDevInfoReq parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static EspDriver.CommEsp.DrvDevInfoReq parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static EspDriver.CommEsp.DrvDevInfoReq parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static EspDriver.CommEsp.DrvDevInfoReq parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static EspDriver.CommEsp.DrvDevInfoReq parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static EspDriver.CommEsp.DrvDevInfoReq parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static EspDriver.CommEsp.DrvDevInfoReq parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static EspDriver.CommEsp.DrvDevInfoReq parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(EspDriver.CommEsp.DrvDevInfoReq prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code CommEsp.DrvDevInfoReq}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:CommEsp.DrvDevInfoReq)
          EspDriver.CommEsp.DrvDevInfoReqOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return EspDriver.internal_static_CommEsp_DrvDevInfoReq_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return EspDriver.internal_static_CommEsp_DrvDevInfoReq_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  EspDriver.CommEsp.DrvDevInfoReq.class, EspDriver.CommEsp.DrvDevInfoReq.Builder.class);
        }

        // Construct using EspDriver.CommEsp.DrvDevInfoReq.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
            getReqIdsFieldBuilder();
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          if (reqIdsBuilder_ == null) {
            reqIds_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            reqIdsBuilder_.clear();
          }
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return EspDriver.internal_static_CommEsp_DrvDevInfoReq_descriptor;
        }

        @java.lang.Override
        public EspDriver.CommEsp.DrvDevInfoReq getDefaultInstanceForType() {
          return EspDriver.CommEsp.DrvDevInfoReq.getDefaultInstance();
        }

        @java.lang.Override
        public EspDriver.CommEsp.DrvDevInfoReq build() {
          EspDriver.CommEsp.DrvDevInfoReq result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public EspDriver.CommEsp.DrvDevInfoReq buildPartial() {
          EspDriver.CommEsp.DrvDevInfoReq result = new EspDriver.CommEsp.DrvDevInfoReq(this);
          int from_bitField0_ = bitField0_;
          if (reqIdsBuilder_ == null) {
            if (((bitField0_ & 0x00000001) != 0)) {
              reqIds_ = java.util.Collections.unmodifiableList(reqIds_);
              bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.reqIds_ = reqIds_;
          } else {
            result.reqIds_ = reqIdsBuilder_.build();
          }
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof EspDriver.CommEsp.DrvDevInfoReq) {
            return mergeFrom((EspDriver.CommEsp.DrvDevInfoReq)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(EspDriver.CommEsp.DrvDevInfoReq other) {
          if (other == EspDriver.CommEsp.DrvDevInfoReq.getDefaultInstance()) return this;
          if (reqIdsBuilder_ == null) {
            if (!other.reqIds_.isEmpty()) {
              if (reqIds_.isEmpty()) {
                reqIds_ = other.reqIds_;
                bitField0_ = (bitField0_ & ~0x00000001);
              } else {
                ensureReqIdsIsMutable();
                reqIds_.addAll(other.reqIds_);
              }
              onChanged();
            }
          } else {
            if (!other.reqIds_.isEmpty()) {
              if (reqIdsBuilder_.isEmpty()) {
                reqIdsBuilder_.dispose();
                reqIdsBuilder_ = null;
                reqIds_ = other.reqIds_;
                bitField0_ = (bitField0_ & ~0x00000001);
                reqIdsBuilder_ = 
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                     getReqIdsFieldBuilder() : null;
              } else {
                reqIdsBuilder_.addAllMessages(other.reqIds_);
              }
            }
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          EspDriver.CommEsp.DrvDevInfoReq parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (EspDriver.CommEsp.DrvDevInfoReq) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.util.List<EspDriver.CommEsp.DrvDevInfoReqId> reqIds_ =
          java.util.Collections.emptyList();
        private void ensureReqIdsIsMutable() {
          if (!((bitField0_ & 0x00000001) != 0)) {
            reqIds_ = new java.util.ArrayList<EspDriver.CommEsp.DrvDevInfoReqId>(reqIds_);
            bitField0_ |= 0x00000001;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
            EspDriver.CommEsp.DrvDevInfoReqId, EspDriver.CommEsp.DrvDevInfoReqId.Builder, EspDriver.CommEsp.DrvDevInfoReqIdOrBuilder> reqIdsBuilder_;

        /**
         * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
         */
        public java.util.List<EspDriver.CommEsp.DrvDevInfoReqId> getReqIdsList() {
          if (reqIdsBuilder_ == null) {
            return java.util.Collections.unmodifiableList(reqIds_);
          } else {
            return reqIdsBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
         */
        public int getReqIdsCount() {
          if (reqIdsBuilder_ == null) {
            return reqIds_.size();
          } else {
            return reqIdsBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
         */
        public EspDriver.CommEsp.DrvDevInfoReqId getReqIds(int index) {
          if (reqIdsBuilder_ == null) {
            return reqIds_.get(index);
          } else {
            return reqIdsBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
         */
        public Builder setReqIds(
            int index, EspDriver.CommEsp.DrvDevInfoReqId value) {
          if (reqIdsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureReqIdsIsMutable();
            reqIds_.set(index, value);
            onChanged();
          } else {
            reqIdsBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
         */
        public Builder setReqIds(
            int index, EspDriver.CommEsp.DrvDevInfoReqId.Builder builderForValue) {
          if (reqIdsBuilder_ == null) {
            ensureReqIdsIsMutable();
            reqIds_.set(index, builderForValue.build());
            onChanged();
          } else {
            reqIdsBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
         */
        public Builder addReqIds(EspDriver.CommEsp.DrvDevInfoReqId value) {
          if (reqIdsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureReqIdsIsMutable();
            reqIds_.add(value);
            onChanged();
          } else {
            reqIdsBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
         */
        public Builder addReqIds(
            int index, EspDriver.CommEsp.DrvDevInfoReqId value) {
          if (reqIdsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureReqIdsIsMutable();
            reqIds_.add(index, value);
            onChanged();
          } else {
            reqIdsBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
         */
        public Builder addReqIds(
            EspDriver.CommEsp.DrvDevInfoReqId.Builder builderForValue) {
          if (reqIdsBuilder_ == null) {
            ensureReqIdsIsMutable();
            reqIds_.add(builderForValue.build());
            onChanged();
          } else {
            reqIdsBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
         */
        public Builder addReqIds(
            int index, EspDriver.CommEsp.DrvDevInfoReqId.Builder builderForValue) {
          if (reqIdsBuilder_ == null) {
            ensureReqIdsIsMutable();
            reqIds_.add(index, builderForValue.build());
            onChanged();
          } else {
            reqIdsBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
         */
        public Builder addAllReqIds(
            java.lang.Iterable<? extends EspDriver.CommEsp.DrvDevInfoReqId> values) {
          if (reqIdsBuilder_ == null) {
            ensureReqIdsIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, reqIds_);
            onChanged();
          } else {
            reqIdsBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
         */
        public Builder clearReqIds() {
          if (reqIdsBuilder_ == null) {
            reqIds_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
          } else {
            reqIdsBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
         */
        public Builder removeReqIds(int index) {
          if (reqIdsBuilder_ == null) {
            ensureReqIdsIsMutable();
            reqIds_.remove(index);
            onChanged();
          } else {
            reqIdsBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
         */
        public EspDriver.CommEsp.DrvDevInfoReqId.Builder getReqIdsBuilder(
            int index) {
          return getReqIdsFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
         */
        public EspDriver.CommEsp.DrvDevInfoReqIdOrBuilder getReqIdsOrBuilder(
            int index) {
          if (reqIdsBuilder_ == null) {
            return reqIds_.get(index);  } else {
            return reqIdsBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
         */
        public java.util.List<? extends EspDriver.CommEsp.DrvDevInfoReqIdOrBuilder> 
             getReqIdsOrBuilderList() {
          if (reqIdsBuilder_ != null) {
            return reqIdsBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(reqIds_);
          }
        }
        /**
         * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
         */
        public EspDriver.CommEsp.DrvDevInfoReqId.Builder addReqIdsBuilder() {
          return getReqIdsFieldBuilder().addBuilder(
              EspDriver.CommEsp.DrvDevInfoReqId.getDefaultInstance());
        }
        /**
         * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
         */
        public EspDriver.CommEsp.DrvDevInfoReqId.Builder addReqIdsBuilder(
            int index) {
          return getReqIdsFieldBuilder().addBuilder(
              index, EspDriver.CommEsp.DrvDevInfoReqId.getDefaultInstance());
        }
        /**
         * <code>repeated .CommEsp.DrvDevInfoReqId req_ids = 1;</code>
         */
        public java.util.List<EspDriver.CommEsp.DrvDevInfoReqId.Builder> 
             getReqIdsBuilderList() {
          return getReqIdsFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilderV3<
            EspDriver.CommEsp.DrvDevInfoReqId, EspDriver.CommEsp.DrvDevInfoReqId.Builder, EspDriver.CommEsp.DrvDevInfoReqIdOrBuilder> 
            getReqIdsFieldBuilder() {
          if (reqIdsBuilder_ == null) {
            reqIdsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                EspDriver.CommEsp.DrvDevInfoReqId, EspDriver.CommEsp.DrvDevInfoReqId.Builder, EspDriver.CommEsp.DrvDevInfoReqIdOrBuilder>(
                    reqIds_,
                    ((bitField0_ & 0x00000001) != 0),
                    getParentForChildren(),
                    isClean());
            reqIds_ = null;
          }
          return reqIdsBuilder_;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:CommEsp.DrvDevInfoReq)
      }

      // @@protoc_insertion_point(class_scope:CommEsp.DrvDevInfoReq)
      private static final EspDriver.CommEsp.DrvDevInfoReq DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new EspDriver.CommEsp.DrvDevInfoReq();
      }

      public static EspDriver.CommEsp.DrvDevInfoReq getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<DrvDevInfoReq>
          PARSER = new com.google.protobuf.AbstractParser<DrvDevInfoReq>() {
        @java.lang.Override
        public DrvDevInfoReq parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new DrvDevInfoReq(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<DrvDevInfoReq> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<DrvDevInfoReq> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public EspDriver.CommEsp.DrvDevInfoReq getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EspDriver.CommEsp)) {
        return super.equals(obj);
      }
      EspDriver.CommEsp other = (EspDriver.CommEsp) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EspDriver.CommEsp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EspDriver.CommEsp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EspDriver.CommEsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EspDriver.CommEsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EspDriver.CommEsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EspDriver.CommEsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EspDriver.CommEsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EspDriver.CommEsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static EspDriver.CommEsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EspDriver.CommEsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EspDriver.CommEsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EspDriver.CommEsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EspDriver.CommEsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CommEsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CommEsp)
        EspDriver.CommEspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EspDriver.internal_static_CommEsp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EspDriver.internal_static_CommEsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EspDriver.CommEsp.class, EspDriver.CommEsp.Builder.class);
      }

      // Construct using EspDriver.CommEsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EspDriver.internal_static_CommEsp_descriptor;
      }

      @java.lang.Override
      public EspDriver.CommEsp getDefaultInstanceForType() {
        return EspDriver.CommEsp.getDefaultInstance();
      }

      @java.lang.Override
      public EspDriver.CommEsp build() {
        EspDriver.CommEsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public EspDriver.CommEsp buildPartial() {
        EspDriver.CommEsp result = new EspDriver.CommEsp(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EspDriver.CommEsp) {
          return mergeFrom((EspDriver.CommEsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EspDriver.CommEsp other) {
        if (other == EspDriver.CommEsp.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EspDriver.CommEsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EspDriver.CommEsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CommEsp)
    }

    // @@protoc_insertion_point(class_scope:CommEsp)
    private static final EspDriver.CommEsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EspDriver.CommEsp();
    }

    public static EspDriver.CommEsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommEsp>
        PARSER = new com.google.protobuf.AbstractParser<CommEsp>() {
      @java.lang.Override
      public CommEsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommEsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommEsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommEsp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public EspDriver.CommEsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommEsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommEsp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommEsp_DrvDevInfoReqId_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommEsp_DrvDevInfoReqId_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommEsp_DrvDevInfoReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommEsp_DrvDevInfoReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020esp_driver.proto\"r\n\007CommEsp\032+\n\017DrvDevI" +
      "nfoReqId\022\n\n\002id\030\001 \001(\005\022\014\n\004type\030\002 \001(\005\032:\n\rDr" +
      "vDevInfoReq\022)\n\007req_ids\030\001 \003(\0132\030.CommEsp.D" +
      "rvDevInfoReqIdb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CommEsp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CommEsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommEsp_descriptor,
        new java.lang.String[] { });
    internal_static_CommEsp_DrvDevInfoReqId_descriptor =
      internal_static_CommEsp_descriptor.getNestedTypes().get(0);
    internal_static_CommEsp_DrvDevInfoReqId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommEsp_DrvDevInfoReqId_descriptor,
        new java.lang.String[] { "Id", "Type", });
    internal_static_CommEsp_DrvDevInfoReq_descriptor =
      internal_static_CommEsp_descriptor.getNestedTypes().get(1);
    internal_static_CommEsp_DrvDevInfoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommEsp_DrvDevInfoReq_descriptor,
        new java.lang.String[] { "ReqIds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
