# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyluba/proto/mctrl_ota.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cpyluba/proto/mctrl_ota.proto\"f\n\x08\x42\x61seInfo\x12\x12\n\ndevVersion\x18\x01 \x01(\t\x12\x11\n\tdevStatus\x18\x02 \x01(\x05\x12\x0f\n\x07\x62\x61ttVal\x18\x03 \x01(\x05\x12\x12\n\ninitStatus\x18\x04 \x01(\x05\x12\x0e\n\x06isTilt\x18\x05 \x01(\x05\"\\\n\x07OtaInfo\x12\r\n\x05otaid\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x10\n\x08progress\x18\x03 \x01(\x05\x12\x0e\n\x06result\x18\x04 \x01(\x05\x12\x0f\n\x07message\x18\x05 \x01(\t\"\x1f\n\x0fToDevGetInfoReq\x12\x0c\n\x04type\x18\x01 \x01(\x05\"\xb7\x01\n\x0fToAppGetInfoRsp\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\'\n\x04type\x18\x02 \x01(\x0e\x32\x19.ToAppGetInfoRsp.InfoCase\x12\x19\n\x04\x62\x61se\x18\x03 \x01(\x0b\x32\t.BaseInfoH\x00\x12\x17\n\x03ota\x18\x04 \x01(\x0b\x32\x08.OtaInfoH\x00\"/\n\x08InfoCase\x12\x08\n\x04\x42\x41SE\x10\x00\x12\x07\n\x03OTA\x10\x01\x12\x10\n\x0cINFO_NOT_SET\x10\x02\x42\x06\n\x04info\"y\n\x08MctrlOta\x12/\n\x13to_dev_get_info_req\x18\x01 \x01(\x0b\x32\x10.ToDevGetInfoReqH\x00\x12/\n\x13to_app_get_info_rsp\x18\x02 \x01(\x0b\x32\x10.ToAppGetInfoRspH\x00\x42\x0b\n\tSubOtaMsgb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pyluba.proto.mctrl_ota_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BASEINFO._serialized_start=32
  _BASEINFO._serialized_end=134
  _OTAINFO._serialized_start=136
  _OTAINFO._serialized_end=228
  _TODEVGETINFOREQ._serialized_start=230
  _TODEVGETINFOREQ._serialized_end=261
  _TOAPPGETINFORSP._serialized_start=264
  _TOAPPGETINFORSP._serialized_end=447
  _TOAPPGETINFORSP_INFOCASE._serialized_start=392
  _TOAPPGETINFORSP_INFOCASE._serialized_end=439
  _MCTRLOTA._serialized_start=449
  _MCTRLOTA._serialized_end=570
# @@protoc_insertion_point(module_scope)
